### ISSUE TITLE
Make Your App Look Awesome on Mobile

### ISSUE THREAD

**Issue by MarcoMorawec** [cryogenx/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by cryogenx** [comment]
in the latest commit I've added some responsiveness to the headed code to make the sites head layout better on mobile. let me know what you think!

[Check out Splurty!](https://splurty-george-welsted.herokuapp.com/)

**Comment by MarcoMorawec** [comment]
:+1: @cryogenx 

One nit-picky thing would be to change how your quotes are displayed, since they overlap with your footer on mobile. That said, this is a pretty small detail, but I figured I point it out.

Here's what I'm seeing:

![screen shot 2015-06-26 at 12 00 28 pm](https://cloud.githubusercontent.com/assets/1474717/8381658/022e1e90-1bfb-11e5-81f0-29c123055902.png)

**Comment by cryogenx** [comment]
ahh I will fix! what device are you using? Im on and iphone 6+ and getting this: 

![image](https://cloud.githubusercontent.com/assets/731595/8381761/bd326f02-1bfb-11e5-84bb-ea1c15ab7b41.png)

p.s. how did you get safari to be dark.. i like it!

**Comment by MarcoMorawec** [comment]
I'm on an iPhone 5 - Now we're getting into the black hole of mobile optimization, so I wouldn't spend too much time on it, since I clearly should upgrade my phone.

PS. Dark safari comes with Jedi powers :) Nah, I think it was an option that I selected in my phone settings, but I don't recall how to do it right now.

**Comment by cryogenx** [comment]
you can see in the latest commit the text scales for smaller viewports, please test and let me know!

**Comment by MarcoMorawec** [comment]
Tested it on iPhone 5 --> :+1:

**Comment by cryogenx** [comment]
Thanks for the input! and testing help!
